name: news
description:

publish_to:


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7
  cached_network_image: ^3.4.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.6
  loading_animation_widget: ^1.3.0
  url_launcher: ^6.3.1
  dropdown_button2: ^2.3.9
  provider: ^6.0.5
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5

dependency_overrides:
  provider: 6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/images/

